# docker-compose.yml
version: '3.7'
services:
  web:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'localhost'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://localhost:${GITLAB_EXTERNAL_PORT}'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'unicode'
        gitlab_rails['db_database'] = '${POSTGRES_DB}'
        gitlab_rails['db_username'] = '${POSTGRES_USER}'
        gitlab_rails['db_password'] = '${POSTGRES_PASSWORD}'
        gitlab_rails['db_host'] = 'db'
        gitlab_rails['smtp_enable'] = ${GITLAB_SMTP_ENABLE}
        gitlab_rails['smtp_address'] = "${GITLAB_SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${GITLAB_SMTP_USER}"
        gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASS}"
        gitlab_rails['smtp_domain'] = "${GITLAB_SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${GITLAB_SMTP_AUTH}"
        gitlab_rails['smtp_enable_starttls_auto'] = ${GITLAB_SMTP_STARTTLS}
        gitlab_rails['smtp_tls'] = ${GITLAB_SMTP_TLS}
        gitlab_rails['smtp_openssl_verify_mode'] = '${GITLAB_SMTP_VERIFY_MODE}'
        gitlab_rails['gitlab_email_from'] = "${GITLAB_EMAIL_FROM}"
        gitlab_rails['gitlab_email_display_name'] = "${GITLAB_EMAIL_DISPLAY}"
        gitlab_rails['gitlab_default_locale'] = 'zh_TW'
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = YAML.load <<-EOS
          main:
            label: 'LDAP'
            host: 'openldap'
            port: 389
            uid: 'uid'
            bind_dn: '${LDAP_BIND_DN}'
            password: '${LDAP_ADMIN_PASSWORD}'
            encryption: 'plain'
            verify_certificates: false
            active_directory: false
            allow_username_or_email_login: true
            base: '${LDAP_BASE}'
        EOS
        nginx['redirect_http_to_https'] = ${GITLAB_NGINX_REDIRECT_HTTP_TO_HTTPS}
        nginx['listen_port'] = ${GITLAB_NGINX_LISTEN_PORT}
        nginx['listen_https'] = ${GITLAB_NGINX_LISTEN_HTTPS}
        nginx['ssl_certificate'] = "${GITLAB_NGINX_SSL_CERTIFICATE}"
        nginx['ssl_certificate_key'] = "${GITLAB_NGINX_SSL_CERTIFICATE_KEY}"
    ports:
      - '8080:80'
      - '${GITLAB_EXTERNAL_PORT}:${GITLAB_EXTERNAL_PORT}'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
      - '${DATA_PATH}/ssl:/ssl'
    networks:
      - gitlab
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: gitlab-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - '${DATA_PATH}/postgres:/var/lib/postgresql/data'
    networks:
      - gitlab
  gitlab-runner:
    build:
      context: ./Dockerfiles/gitlab-runner
    image: custom-gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    environment:
      - GITLAB_RUNNER_TOKEN=${GITLAB_RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '${DATA_PATH}/gitlab-runner:/etc/gitlab-runner'
      - '${DATA_PATH}/ssl:/ssl'
      - '${DATA_PATH}/template:/template'
    networks:
      - gitlab
    extra_hosts:
      - host.docker.internal:host-gateway
  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    ports:
      - "8389:389"
      - "8636:636"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    volumes:
      - '${LDAP_HOME}/backup:/data/backup'
      - '${LDAP_HOME}/data:/var/lib/openldap'
      - '${LDAP_HOME}/config:/etc/openldap/slapd.d'
      - '${LDAP_HOME}/certs:/assets/slapd/certs'
      - '${DATA_PATH}/bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom'
    command: [--copy-service,  --loglevel, debug]
    networks:
      - gitlab
  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:latest
    ports:
      - "${PHPLDAPADMIN_PORT}:80"
    environment:
      - PHPLDAPADMIN_HTTPS="false"
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    links:
      - openldap
    depends_on:
      - openldap
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network